server:
  port: 9191
spring:
  application:
    name: gateway-api

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: BUS-SERVICE
          uri: lb://BUS-SERVICE
          predicates:
            - Path=/bus/**
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/**
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        - id: TRAIN-SERVICE
          uri: lb://TRAIN-SERVICE
          predicates:
            - Path=/train/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
                
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}