server:
  port: 9191
spring:
  application:
    name: gateway-api

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: BUS-SERVICE
          uri: lb://BUS-SERVICE
          predicates:
            - Path=/bus/**
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/**
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        - id: TRAIN-SERVICE
          uri: lb://TRAIN-SERVICE
          predicates:
            - Path=/train/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
#            - Path=/api/v2/user/**
#          filters:
#            - RewritePath=/user/(?<segment>.*),/api/v1/user/${segment}
                
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}