server:
  port: 8070
spring:
  application:
    name: bus-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: ${JDBC_URL:jdbc:mariadb://multi-ticket-booking.cvogtr4zthsb.us-east-1.rds.amazonaws.com:3306/busservice}
#    username: ${DB_USER:admin}
#    password: ${DB_PASSWOED:welcome1}
    url: ${JDBC_URL:jdbc:mariadb://localhost:3306/businfo}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

logging:
  file:
    name: logs/busservice.log
    
management:
  endpoints:
    web:
      exposure:
        include: "*"