server:
  port: 8060
spring:
  application:
    name: hotel-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${JDBC_URL:jdbc:mariadb://multi-ticket-booking.cvogtr4zthsb.us-east-1.rds.amazonaws.com:3306/hotelsinfo}
    username: ${DB_USER:admin}
    password: ${DB_PASSWOED:welcome1}
    hikari:
      maximum-pool-size: 10
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
      

logging:
  file:
    name: logs/hotelservice.log
    
management:
  endpoints:
    web:
      exposure:
        include: "*"