server:
  port: 8040
spring:
  application:
    name: order-service
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

    
logging:
  file:
    name: logs/orderservice.log

management:
  endpoints:
    web:
      exposure:
        include: "*"