server:
  port: 8060
spring:
  application:
    name: hotel-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: ${JDBC_URL:jdbc:mariadb://multi-ticket-booking.cvogtr4zthsb.us-east-1.rds.amazonaws.com:3306/hotelsinfo}
#    username: ${DB_USER:admin}
#    password: ${DB_PASSWORD:welcome1}
    url: ${JDBC_URL:jdbc:mariadb://localhost:3306/hotelinfo}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
      

logging:
  file:
    name: logs/hotelservice.log
    
management:
  endpoints:
    web:
      exposure:
        include: "*"